version: '3'
name: api-rails
services:
    postgres:
        image: postgres:13.2-alpine
        container_name: api-db
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        networks:
            - api-bridge-network
        ports:
            - "5432:5432"   
        volumes:
            - ./db/data:/var/lib/postgresql/data

    api:
        image: ruby:3.0.0-alpine3.13
        container_name: api-app

        environment:
            - DATABASE_URL=postgres://postgres:postgres@dbapi:5432
            - POSTGRES_USER=postgres

        networks:
            - api-bridge-network
        ports:
            - "3000:3000"    
        volumes:
            - ./api:/api


networks:
    api-bridge-network:
        external: true
        name: api-bridge-network

volumes:
    api-db-data:
        external: true
        name: api-db-data
    api-path:
        external: true
        name: api-path